version: '3'

services:
  web:
    build: .
    volumes:
      - static_volume:/src/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=141.11.184.153,localhost,127.0.0.1

  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume: